baseURL = 'https://nandakumar649.github.io'
languageCode = 'en-gb'
title = "Nanda Bala"
theme = "hugo-coder"
author = "Nanda Bala"
description = 'Profile Page'
avatar = 'avatar.png'
ignoreLogs = ['warning-goldmark-raw-html']
#[menu]
#  [[menu.main]]
#    identifier = "home"
#    name = "Home"
#    icon = "hugo-home"
#    url = "/"
#    weight = 1

#[params]
#  # Author
#  author = "Nanda Bala"
#  # Description
#  description = "Senior DevOps Engineer"
#  avatar = 'images/avatar.png'
#  # Social links
#  [[params.social]]
#    icon = "brand-github"
#    name = "My Github"
#    url = "https://github.com/nandakumar649"
#  [[params.social]]
#    icon = "brand-x"
#    name = "X"
#    url = "https://x.com/nandakumar649"
#  [[params.social]]
#    icon = "brand-linkedin"
#    name = "LinkedIn"
#    url = "https://www.linkedin.com/in/nandakumar649/"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "NandaBala"

[markup.highlight]
style = "github-dark"

[params]
  author = "Nanda Bala"
  info = "Senior DevOps Engineer"
  description = "Nanda Bala personal website"
  keywords = "blog,developer,personal"
  avatarurl = 'images/avatar.png'

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2012

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/nandakumar649"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 2
  url = "https://x.com/nandakumar649"

# Menu links
[[menu.main]]
  name = "Resume"
  weight = 1
  url  = "resume/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"