---
name: Pull Request Labeler
run-name: ${{ github.actor }} has triggered the job
on:
  - pull_request_target
  - pull_request

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 1
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
